ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDraR0ixEOlpP3Ygr3AkcjUsAJf+xHi2Yia3E4/alPkls8SjNBGmCS3Fnr1z4bGFVP+5TQSNzqhIgtD5+VXmMh34WRPRmzzck7H/JQ5s6FGlzQeLrz2kZB2GCnsL4z79keem7DOgvdGojai9NkbJkoQqshwdEif85gvUl7fLXqiWE90KdIJbT3+BLvuZDAs+qr7tbD5A8/u7JK/GwGHu01CtNFZ5UHnAfZ5z4dQg7Cw0GgwegbA37pO/DvdpQ8JVvD1GsdKOZyIdtMiEPR1sS+sRXTqliw4YnI+ZzyaXx6s4pGbxEEoph8n06iF6EGD1w6l+8jfnU09VDKz8KIM/ICQ8lYRxJ5lRCrX/QrStSI6aActAxxm54ftYu6Wa/XKKiAPXLPjV5xNAlW7eta7kfjqKciooI8tWBC6RAF7Bx3rIkj8QANG8FmJWzKgAxhibx/jc7OPNpfoWC5C6CCSIktC6g0Ku7qUkzAZfcn5usr2JAvQPp3+aYFacjEYISVCyYLOANQffYAE66QiAyb7N117UWS2QUW9U7V9znLohAw+VbSVwUYkTrJ7sLnl+lEP/DL9mndxrz5awU0zazMa6xk17HFGYWTCCCPhRyMrrz+AfkHzMu/LAgfr64PhSUXuPfq1yXN5C6b3+lwtWbH4uOQ4UEcCJlNYrUvD1MNmaruIDw== dev@yeah.si
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+2q1QBGE2fBrSHIqGjmdh+qdYV4VtQZOFi7MqW83BVj/vS16kfiGJGw0ke+yh0sGZK5aeaXsb7kuayngXXO7NpTgvzy9Li2T0vvzTNdsgr5Jysg66u7JQwYvYhtYHpZraa4PgQBEg7Fc7qwW/ULfTmIYdq6hWobuaPpE4DH3cG/mon9aS4uy+ULJkStvnTkfF2onlGup9mDIFlRnmfg1N4Ufl+WpThg7llvyPvyO4vUnjiqsJu66Vom6Yxn3IZU9dRF7qeJ4V/eUnhc7BsDaZZOWYbjUX+OguA2JqpgQ3+77KBFBpFJzg5prC5TsZAqCTlSdxIGTAXb1eZOoiAM4H sebastian.fuss@senacor.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgTFUPwvVwqJ72A7rYSzZDWdIvUHOnG9wTlIPcq9oBDmiUBAvOFMZgnZ9u+nf7UnF9X8rhQyN8wYetQ7ObNSQmStJ8/1pmNSRqf6WfDB1CFPWcu1PhU8H0YGXbRdJBDELs/cLy+tQ5dpL2O4d9jyxrRtwh8drPO70l8OrmaM6+0wRFhc1nz0hcNMNs9LDQslRBNIOMX9oqvmnaDHVOBnMc57lthC7NxVcD3qsEynk5tRhJ5LKzpjU7fZ4KOHwWp8efWx+DsgAvkG+wJ0w6lKeuMbjcmb8gSZID66LsY9H2JJK2hLtXvtTxWjby7uoEgdYuudzrXRDZ5nEbRtxKGRHZ michi@rancher
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUW53Eb/6FrP6ijwjepYRxjjf+8hg/WdhJ83XMo79MRvxzxhivruc8qNs5m6hWndTf3JjJijZpEpLdtAH5LpclnywQLC7RIHBUq6mP7cHb7CmAOdj0/ULZ7h72193ud0VxBNE1lVS3NrFIS1gPAGSDYT4ZtcjcgxpuADWNfwZc18kDdBI7FycpqUCTGnMbJHN7TXetuAcSChcVL+8tAuJhjtascIJD/JbPtdRQ0KCwI2DcfLHeVx2NeF+qXf5bW7649E+1jFh73zRlLybv8NHXEvZmnh2v6atBO5um/MGgD33I6g5+J4IIl5X87O/m5TEKq1UjLTreiHwSFJSzsFfl jpoellat@POEJU-AMBP-2.local
hostname: rancher1
rancher:
  docker:
    engine: docker-17.03.2-ce
    tls: false
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - 10.90.0.15
      - 10.89.0.15
      - 8.8.8.8
      - 8.8.4.4
    interfaces:
      eth0:
        address: 10.90.0.87/24
        dhcp: false
        gateway: 10.90.0.1
        mtu: 1500
      eth1:
        dhcp: true
      lo:
        address: 127.0.0.1/8
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
